/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package FileManagement;

import EDD.Lista;
import EDD.Nodo;
import Grafos.Grafo;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author jonathanpizzurro
 */
public class subirArchivo extends javax.swing.JFrame {

    /**
     * Creates new form subirArchivo
     */
    public subirArchivo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jButton1)
                .addContainerGap(448, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(184, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(144, 144, 144))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        int selection = fileChooser.showOpenDialog(this);
        if (selection == JFileChooser.APPROVE_OPTION) {
            File archivo = fileChooser.getSelectedFile();
            // Crear un StringBuilder para almacenar el contenido del archivo
            StringBuilder contenido = new StringBuilder();

            List<Lista> arrayListDeListas = new ArrayList<>();
            List<String> arrayListDeListasRelaciones = new ArrayList<>();
            boolean comprobacion = false;
//            String usuario1 = null;
//            String usuario2 = null;

            try ( BufferedReader lector = new BufferedReader(new FileReader(archivo))) {
                String linea;
                while ((linea = lector.readLine()) != null) {
                    if (linea.equals("usuarios")) {
                        linea = lector.readLine();
                        comprobacion = true;
                    } else if (linea.equals("relaciones")) {
                        comprobacion = false;
                    }
                    if (comprobacion) {
                        String[] lineArray = linea.split(",");
                        String usuario1 = lineArray[0];
                        Nodo nodo = new Nodo(usuario1);
                        Lista lista = new Lista();

                        if (arrayListDeListas.isEmpty()) {
                            lista.insertar_inicio(nodo);
                        } else {
                            lista.insertar_final(nodo);
                        }
                        arrayListDeListas.add(lista);

                    } else {
                        linea = lector.readLine();
                        arrayListDeListasRelaciones.add(linea);

                    }

                }
            } catch (IOException e) {
                System.out.println("Error al leer los usuarios del archivo: " + e.getMessage());
            }

            Lista[] arrayDeListas = arrayListDeListas.toArray(new Lista[0]);
            Grafo grafo = new Grafo(arrayDeListas, arrayDeListas.length);
            for (String linea : arrayListDeListasRelaciones) {
                String[] lineArray = linea.split(",");
                if (lineArray.length >= 2) { // Verificar si la línea tiene al menos dos elementos
                    String usuario1 = lineArray[0].trim();
                    String usuario2 = lineArray[1].trim();
                    // Luego, puedes utilizar estos valores para realizar alguna operación
                    grafo.insertar_relacion(usuario1, usuario2);
                }
            }
         //   grafo.imprimir();

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(subirArchivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(subirArchivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(subirArchivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(subirArchivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new subirArchivo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
